### ISSUE TITLE
I can't generate template because of relative route issue.

### ISSUE THREAD

**Issue by hayden1992** [moul/protoc-gen-gotemplate#184]
I'm getting this error while compile sample proto.
I've tried with relative or absolute path but none of them didn't work.
Did anyone experience this kind of issue?

Many thanks.

![image](https://github.com/user-attachments/assets/7b3a9264-68e6-4a4b-bb3f-d26445b4ef4a)

2024/09/06 03:43:24 new encoder: file="example.proto" service="RouteGuide" template-dir="./templates"
2024/09/06 03:43:24 new template: "example.txt.tmpl"
panic: Rel: can't make D:\suren\go-sandbox\gotemplate relative to C:\Users\1\go/src

goroutine 1 [running]:
moul.io/protoc-gen-gotemplate/helpers.(*GenericTemplateBasedEncoder).Files(0xc000286e60)
        C:/Users/1/go/pkg/mod/moul.io/protoc-gen-gotemplate@v1.11.3/helpers/encoders.go:211 +0x469
moul.io/protoc-gen-gotemplate/helpers.ParseParams(0xc0000c5200)
        C:/Users/1/go/pkg/mod/moul.io/protoc-gen-gotemplate@v1.11.3/helpers/parameters.go:127 +0xd72
main.main()
        C:/Users/1/go/pkg/mod/moul.io/protoc-gen-gotemplate@v1.11.3/main.go:31 +0x1f0
--gotemplate_out: protoc-gen-gotemplate: Plugin failed with status code 2.

**Comment by hayden1992** [comment]
I found it works on ubuntu so I'm closing this issue.
Thank you.
